# 服务器端口配置
server:
  port: 8081
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.szdx.svc.cluster.local:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Root123456
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
# 配置mybatis
mybatis:
  type-aliases-package: com.tagging.entity # entity 位置
  mapper-locations: mapper/*.xml # xml mapper 位置
  configuration: # 其他配置
    map-underscore-to-camel-case: true

# mapper
mapper:
  mappers: com.tagging.dao.base.BaseDao # base mapper
  identity: MYSQL

# log
logging:
  config: classpath:logback-spring.xml

# minio
minio:
  url: http://192.168.159.11:34845
  accessKey: minioadmin
  secretKey: minioadmin
  localUrl: /data
  videoBucket: video
  mottxtBuket: mottxt
  imgBuket: img
  motimgBuket: motimg
  txtBuket: txt
  xmlPath: xml
  serverFilePath: /data/server

# yolo5
# local是yolo算法地址
# execute是相应的python解释器地址
yolo5:
  localUrl: /app
  executeUrl: /root/miniconda3/envs/Auto/bin
  pythonName: ./python3.7
